name: Deploy to EC2 ğŸš€

on:
  push:
    branches:
      - "main" # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout the repository
      - name: Checkout current branch âœ…
        uses: actions/checkout@v2

      # 2ï¸âƒ£ Set up SSH key and whitelist EC2 IP address
      - name: Set up SSH key and whitelist EC2 IP address ğŸ»â€â„ï¸
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 3ï¸âƒ£ Create .env file dynamically
      - name: Create .env file dynamically ğŸ§¨
        env:
          ENV: ${{ secrets.ENV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "ENV=${ENV}" >> env
          echo "EC2_USERNAME=${EC2_USERNAME}" >> env

      # 4ï¸âƒ£ Copy files to remote server using SCP
      - name: Copy files to remote server ğŸš™
        run: |
          scp -i ~/.ssh/id_rsa -r ./* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

      # 5ï¸âƒ£ Run Bash script to deploy the app
      - name: Run Bash Script To Deploy App ğŸš€
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "chmod +x ./deploy.sh && ./deploy.sh"

      # 6ï¸âƒ£ Clean up SSH key
      - name: Clean up SSH key ğŸ§¹
        if: always()
        run: rm -f ~/.ssh/id_rsa
